-- 创建16个分库
CREATE DATABASE IF NOT EXISTS study_db_00;
CREATE DATABASE IF NOT EXISTS study_db_01;
CREATE DATABASE IF NOT EXISTS study_db_02;
CREATE DATABASE IF NOT EXISTS study_db_03;
CREATE DATABASE IF NOT EXISTS study_db_04;
CREATE DATABASE IF NOT EXISTS study_db_05;
CREATE DATABASE IF NOT EXISTS study_db_06;
CREATE DATABASE IF NOT EXISTS study_db_07;
CREATE DATABASE IF NOT EXISTS study_db_08;
CREATE DATABASE IF NOT EXISTS study_db_09;
CREATE DATABASE IF NOT EXISTS study_db_10;
CREATE DATABASE IF NOT EXISTS study_db_11;
CREATE DATABASE IF NOT EXISTS study_db_12;
CREATE DATABASE IF NOT EXISTS study_db_13;
CREATE DATABASE IF NOT EXISTS study_db_14;
CREATE DATABASE IF NOT EXISTS study_db_15;

-- 显示所有数据库
SHOW DATABASES; 